### ISSUE TITLE
sendUpdateToFlowdock fails with XLR 7.5

### ISSUE THREAD

**Issue by jdewinne** [xebialabs-community/xlr-flowdock-plugin#8]
java.lang.NullPointerException: null
                at com.xebialabs.xlrelease.flowdock.plugin.FlowdockRepositoryService.setFlowdockConfigurations(FlowdockRepositoryService.java:52)
                at com.xebialabs.xlrelease.flowdock.plugin.FlowdockRepositoryService.isFlowdockEnabled(FlowdockRepositoryService.java:38)
                at com.xebialabs.xlrelease.flowdock.plugin.FlowdockListener.sendUpdateToFlowdock(FlowdockListener.java:42)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at nl.javadude.t2bus.EventHandler.handleEvent(EventHandler.java:88)
                at nl.javadude.t2bus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:48)
                at nl.javadude.t2bus.event.strategy.BaseEventHandlerStrategy.handle(BaseEventHandlerStrategy.java:15)
                at nl.javadude.t2bus.T2Bus.handle(T2Bus.java:373)
                at nl.javadude.t2bus.T2Bus.dispatch(T2Bus.java:359)
                at nl.javadude.t2bus.T2Bus.dispatchQueuedEvents(T2Bus.java:341)
                at nl.javadude.t2bus.T2Bus.post(T2Bus.java:275)
                at com.xebialabs.deployit.event.EventBusHolder.publish(EventBusHolder.java:53)
                at com.xebialabs.xlrelease.XLReleaseServer.start(XLReleaseServer.java:362)
                at com.xebialabs.xlrelease.XLReleaseBootstrapper.startServer(XLReleaseBootstrapper.java:108)
                at com.xebialabs.xlrelease.XLReleaseBootstrapper.start(XLReleaseBootstrapper.java:75)
                at com.xebialabs.xlrelease.XLReleaseBootstrapper.main(XLReleaseBootstrapper.java:53)

**Comment by droberts2013** [comment]
Work is in progress to resolve in XL Release 8.0.
